randovania/open-samus-returns-rando

open_samus_returns_rando/files/custom_scenario.lua
open_samus_returns_rando/files/levels/s000_surface.lc.lua

Auto-drain surface hazardous pool.
Auto-enable all hazardous pool spawngroups, usables, and triggers.

Pull new changes and re-apply previous changes

---

open_samus_returns_rando/files/custom_scenario.lua
open_samus_returns_rando/files/levels/s000_surface.lc.lua
open_samus_returns_rando/files/levels/s010_area1.lc.lua
open_samus_returns_rando/files/levels/s025_area2b.lc.lua
open_samus_returns_rando/files/levels/s028_area2c.lc.lua
open_samus_returns_rando/files/levels/s030_area3.lc.lua
open_samus_returns_rando/files/levels/s040_area4.lc.lua
open_samus_returns_rando/files/levels/s060_area6.lc.lua
open_samus_returns_rando/files/levels/s070_area7.lc.lua
open_samus_returns_rando/files/levels/s090_area9.lc.lua

Enable the metroid intro fights even if you enter from the wrong door.
Auto-drain all other Hazardous pools and enable correct cameras.

Hazardous pools and metroid intro fights.

---

open_samus_returns_rando/files/randomizer_powerup.lua
open_samus_returns_rando/pickup.py

fixes #62
Also now uses Spider Ball as the template bmsad so breakable blocks don't get deleted. Related to #8

Fix collecting Gravity Suit in liquids not removing effects

---

open_samus_returns_rando/files/schema.json
open_samus_returns_rando/samus_returns_patcher.py
open_samus_returns_rando/specific_patches/game_patches.py
tests/test_files/starter_preset_patcher.json

Beam Doors, including Charge, now need there respective beam to open. Charge Doors can still be opened by Beam Burst.
Related #42

Remove PB weakness from Beam Doors

---

open_samus_returns_rando/files/levels/s100_area10.lua
open_samus_returns_rando/files/randomizer_powerup.lua
open_samus_returns_rando/files/schema.json
open_samus_returns_rando/lua_editor.py
open_samus_returns_rando/model_data.py
open_samus_returns_rando/samus_returns_patcher.py
tests/test_files/starter_preset_patcher.json

The Baby location can now be shuffled, as well at the Baby being shuffle-able to other pickup locations
Fixes #18 
Related to #40

Support Shuffled Baby

---

open_samus_returns_rando/files/schema.json
open_samus_returns_rando/patcher_editor.py
open_samus_returns_rando/specific_patches/game_patches.py
tests/test_files/starter_preset_patcher.json

Related to #57
Shortcut option disabled
Shortcut option enabled

Support option to remove grapple blocks

---

open_samus_returns_rando/files/heatzone.lua
open_samus_returns_rando/lua_editor.py

Something in some rooms make the sound immediately stop.
I delay it now to the next game loop cycle with `Game.AddSF(0.0, "HeatZone.PlaySound", "")` and it worked in the room in area4 and area5.
I hope that it fixes all rooms

Fix heat sound not playing

---

open_samus_returns_rando/files/levels/s050_area5.lua

It's not ideal but does work. Without this, a room reload is necessary or attempt to travel to a different collision camera with incorrect visuals/geometry active. Probably will just end up excluding this save as a valid spawn to make it easier.

Attempted fix for pre-chase layers not being removed if starting from chase save

---

open_samus_returns_rando/files/schema.json
open_samus_returns_rando/specific_patches/game_patches.py
tests/test_files/crumble_blocks.json

Adds an option to change the crumble blocks after Scan Pulse and leaving Area 1 to be Power Beam blocks. This is to open up the rando a bit more. These changes affect the following:
- For Surface, this means that a player can more safely access the Alpha section without being forced to have/find Charge Beam to leave the area.
- For Area 1, this means that Spider Ball is no longer hard required to leave the area. Even though Phase Drift can be an alternative to Spider, Spider is more likely to be placed early due to its overall usefulness.
I couldn't figure out how to delete the blocks and remove the textures, as the textures seem to be left behind. A more ideal situation would be to remove the blocks entirely. Might also be worth splitting this option up in the future, as they are …

Support option for removing crumble blocks in S and A1

---

open_samus_returns_rando/lua_editor.py
open_samus_returns_rando/specific_patches/heat_room_patches.py

- Use `TG_Heat_033` because `TG_Heat_004` removed the metroid (this is so stupid).
- Replace `\n` in caption because otherwise it is breaking the lua file.

Random fixes

---

open_samus_returns_rando/files/custom_savestation.lua
open_samus_returns_rando/files/custom_ship.lua

Copy & Paste error. It defines a function to call so parentheses needs to be removed.

Remove parentheses

---

open_samus_returns_rando/specific_patches/door_patches.py

The flag that changed one-way doors to act like two-way doors wasn't being set for the copied beam covers. Calling the one-way patch first fixes this issue.

Fix One-Way Locked Doors with Beam Covers

---

open_samus_returns_rando/files/schema.json
open_samus_returns_rando/specific_patches/game_patches.py

I'm making this an option instead of forced because it has big logical implications of how to travel the planet.

Add option to traverse Area 8 backwards

---

open_samus_returns_rando/files/custom_scenario.lua
open_samus_returns_rando/files/levels/s025_area2b.lua
open_samus_returns_rando/files/levels/s030_area3.lua
open_samus_returns_rando/files/levels/s033_area3b.lua
open_samus_returns_rando/files/levels/s036_area3c.lua
open_samus_returns_rando/files/levels/s040_area4.lua
open_samus_returns_rando/files/levels/s050_area5.lua
open_samus_returns_rando/files/levels/s070_area7.lua
open_samus_returns_rando/files/templates/metroid_template.lua
open_samus_returns_rando/specific_patches/metroid_patches.py
tests/test_files/metroid_2b.json

- Ensures the Gamma in area2b always spawns regardless of entrance
- Ensures the Omega in area7 always spawns regardless of entrance
- Fixes Metroid radars not ending
- Fixes #135

Fix Metroids

---

open_samus_returns_rando/files/levels/s040_area4.lua
open_samus_returns_rando/files/levels/s060_area6.lua
open_samus_returns_rando/files/levels/s065_area6b.lua
open_samus_returns_rando/files/levels/s067_area6c.lua

Fixes #45 
We update progressive models `OnSubAreaChange` and I just added the global scenario variant to each scenario specific file. Oversight from me was, that there are scenario specific files which do not declare it at all. Hence they didn't showed up when I just  turned my brain off, searched for `OnSubAreaChange` and copy pasted the line.
This also explains
> Edit: I collected the Screw Attack locked item in Area 5 Exterior and then Progressive Suit (top of the same room) suddenly appeared. Something weird is going on.
because models are also updated if you collect any item which was the only way to make the items visible at all for the missing scenarios.

Fix invisible progressives

---

open_samus_returns_rando/files/randomizer_powerup.lua

The used `capacity` variable is already the increased one in the case.

Fix that aeion energy upgrades are doubled

---

open_samus_returns_rando/files/randomizer_powerup.lua

Since the pickups in the Digger chase room are now in their correct positions, they are now underwater. Update the water triggers accordingly if either pickup is a suit.

Disable Liquids in area5 if suit

---

open_samus_returns_rando/files/randomizer_powerup.lua

- Fixes Missiles not properly increasing current ammo when Missile tanks are collected
- Adds QoL where collecting a tank now updates the current value to match the max value, so low ammo counts are less of an issue

Set ammo current value equal to max value on pickup

---

open_samus_returns_rando/pickup.py
open_samus_returns_rando/specific_patches/door_patches.py

- Removed the shield copy
- Ensures that surface and surfaceb is the same item by special case it (which what it really is!)

Deal with weird room being present in surface and surfaceb

---

open_samus_returns_rando/files/levels/s000_surface.lua
open_samus_returns_rando/files/levels/s020_area2.lua
open_samus_returns_rando/files/levels/s025_area2b.lua
open_samus_returns_rando/files/levels/s033_area3b.lua
open_samus_returns_rando/files/levels/s060_area6.lua
open_samus_returns_rando/files/levels/s070_area7.lua
open_samus_returns_rando/specific_patches/metroid_patches.py

Did not test most of these since it requires https://github.com/randovania/mercury-engine-data-structures/pull/88 to be merged first, otherwise rooms break
- Added checkpoints to all but two multi-room Metroids (skipped ones connect to an item room so checkpoint isn't that important)
- Renamed Gamma 2b checkpoints to match the vanilla naming scheme

Add missing checkpoints for most multi-entrance Metroids

---

open_samus_returns_rando/files/levels/s070_area7.lua
open_samus_returns_rando/files/levels/s100_area10.lua
open_samus_returns_rando/files/levels/s110_surfaceb.lua

I don't really know what this is doing.
Does Samus has a different model / mesh / hitbox / whatever during the boss fights?
Following the logic during, entering a boss fights makes `C01_Body_Ch` not visible but `C01_Combat_Ch`. If you die or beat the boss, it's flipped again.
And with only varia it looks like there is no `C01_Combat_Ch` and that's why samus is invisible.
Beat ridley with varia and this patch. If it breaks something with gravity suit on, we maybe need to make it check for the suit etc.

Disable `SetLowModelsVisibility` for samus during boss fights

---

open_samus_returns_rando/custom_pickups.py
open_samus_returns_rando/pickup.py
open_samus_returns_rando/samus_returns_patcher.py
open_samus_returns_rando/specific_patches/door_patches.py
open_samus_returns_rando/specific_patches/map_icons.py

- Adds new map icon for Baby Metroid pickup
- Changes all item icons to open circles (excluding Aeion Ability Artifacts and Metroids)
- Changes all removed acid tiles to be blue from purple
- Updates door icons to match patcher changes
- Fixes #15

Update Map icons

---

open_samus_returns_rando/files/levels/s100_area10.lua
open_samus_returns_rando/files/templates/custom_init.lua
open_samus_returns_rando/samus_returns_patcher.py

- Removes the Larva intro cutscene
- Adds 10 Metroids to the Metroid counter (should this only be added on when in Area 8? Would this cause confusion in routing?)
- Prevents a door from locking if entering the room with Larva_005 to remove a softlock

Fix Area 8 Larvas

---

open_samus_returns_rando/files/levels/s070_area7.lua
open_samus_returns_rando/files/levels/s100_area10.lua
open_samus_returns_rando/files/levels/s110_surfaceb.lua

This activates the low poly model for fights if the player has gravity suit.
It's not possible for other suits because there are no different models and samus would be invisible.

Use low poly model if player has gravity suit

---

open_samus_returns_rando/pickup.py

Probably much better in memory consumption to use one bmsad per item instead of per location. That's reducing the required custom bmsads by something like over 100 files.
(Should be rebased later. Accidentally, have the chozo seal dna stuff in here)

Create bmsad per item and reuse them instead of creating a bmsad for each location

---

open_samus_returns_rando/files/schema.json
open_samus_returns_rando/samus_returns_patcher.py

Replaces `A new file will be created.` and `Current data will be erased.|Start a new game in {difficulty} mode?` with the seed hash. There is probably a way to add the hash to the title screen, but that would require creating new text since the copyright is actually an image and not text.

Support displaying seed hash when making a file

---

open_samus_returns_rando/specific_patches/map_icons.py

I did not properly fix the map tiles last time. It ended up breaking the tiles. This fix actually covers the edge case of tanks and doors sharing the same map tile. As it turns out, All items are listed first, so no need to set the variable there. Doors, however, will vary depending on other actors, thus require the variable.

Fixing map tiles again

---

src/open_samus_returns_rando/files/randomizer_powerup.lua
src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/files/templates/custom_init.lua
src/open_samus_returns_rando/lua_editor.py
src/open_samus_returns_rando/pickups/pickup.py

Adds the three amiibo Reserve Tanks as items, and allows them to be shuffled. They currently use their respective tank model in game and the Aeion Refill Orb FX until we have custom models/textures. Fixes #22 
Current issue is that the HUD doesn't update unless the bottom screen changes (pause, idle screen). The tanks still work but there is no game pause when the reserve is activated and it just happens, which is jarring. Ideally, a proper fix is implemented before merging, but not mandatory.
This PR also adds missing FX for itemspheres.
**Energy Reserve Tank**
https://github.com/randovania/open-samus-returns-rando/assets/38679103/86eed34b-cf78-4f16-8824-eca19fd2afe7
**Missile Reserve Tank**
https://github.com/randovania/open-samus-returns-rando/assets/38679103/b1290105-b7f3-4e50-bc11-edc …

Support enabling/shuffling amiibo Reserve Tanks

---

src/open_samus_returns_rando/pickups/pickup.py

The dict keeps being filled if you try to make more than one export in a row via randovania because it is static.
So, I clear it before loop through the pickups.

Empty the static dict when start patching.

---

src/open_samus_returns_rando/lua_editor.py

Need to unlock the ammo by using the `_MAX` otherwise they will be locked until you pick up the first tank.

Unlock starting ammo if main item is in inventory

---

src/open_samus_returns_rando/lua_editor.py
src/open_samus_returns_rando/pickups/pickup.py

I don't know if the `sound_fx` changes are exactly necessary, but this makes the custom bmsads more accurate to the vanilla ones.
Also changes the DNA pickup sound to be the jingle that plays when the hazardous is removed. This is more appropriate and akin to Artifact/Key collection being unique.

More pickup adjustments

---

src/open_samus_returns_rando/files/levels/s040_area4.lua

Not ideal as it doesn't truly fix the issue, but it prevents the memory errors (and a crash on console). A proper fix in the future would be better.
Fixes #209 temporarily
https://github.com/randovania/open-samus-returns-rando/assets/38679103/2780fd7d-6141-4c90-bf4c-6a7b3437fc6e

Temporary fix for Area 4 Gamma Error

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

Prevents an unnecessary and pointless softlock while keeping the logic intact

Change Save Screw Blocks in A7 from Screw to be Shot

---

src/open_samus_returns_rando/files/levels/s110_surfaceb.lua

Fixes being able to bypass the DNA check if entering the Landing Site from a different cc

Completely prevent accessing Ridley early

---

src/open_samus_returns_rando/specific_patches/metroid_patches.py

Reenables the invulnerability field when defeating a Metroid. Fixes a softlock that occurs when dying the same time the item popup appears.
https://github.com/randovania/open-samus-returns-rando/assets/38679103/25b7e592-14d7-4bc5-9e3e-545d44c89e84

Disable damage when Metroid dies

---

src/open_samus_returns_rando/pickups/pickup.py

`spinattack.bcptl` is just cooler :)
https://github.com/randovania/open-samus-returns-rando/assets/38679103/e36ea666-9366-42bf-806f-aac40555076e

Use less obstructive fx for Reserve Tanks

---

src/open_samus_returns_rando/files/templates/randomizer_powerup.lua

- The suit model now properly updates when suits are not progressive (Power -> Gravity now uses Gravity model instead of Varia)
- The check for enabling/disabling triggers has been overhauled
- Adds in some triggers that were unaccounted for
- Combines both functions into a more streamlined one
- Checks if Samus is inside a trigger and only disables that specific one instead of disabling all of them in the scenario
- Accounts for all liquids (acid, lava, water) regardless if they normally have an item or not
- This only applies to Multiworld, as it could be possible to receive Gravity while in one of these triggers which would force the player to reload their save
- Removes unused/uncessary function calls elsewhere

Improve disabling liquid actors if collecting Gravity

---

src/open_samus_returns_rando/files/levels/s050_area5.lua
src/open_samus_returns_rando/misc_patches/spawn_points.py

This improves the previous temporary fix by spawning at a newly created actor, which fixes the memory issues. If a blackboard prop exists that could be loaded for the chase being completed then that would be the ideal solution.
Fixes #249

Fix memory errors if spawning at Diggernaut Chase Save

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

I increased all enemies except for bosses and Blobthrower, the latter already has a higher chance of 30%
Related to #229

Increase PB drop chance of nearly all enemies

---

src/open_samus_returns_rando/specific_patches/heat_room_patches.py

Heated Gamma collision cameras were missing the heat actor being added to the entity groups

Fix post-Gamma fight rooms not being heated

---

src/open_samus_returns_rando/specific_patches/door_patches.py
src/open_samus_returns_rando/specific_patches/map_icons.py

- Make the Super door connecting to Supers Room be double sided
- Certain shield tiles were incorrectly being changed to Power while their shields were active. Now all shields should be properly shown on the map

Door and Map updates

---

src/open_samus_returns_rando/files/levels/s100_area10.lua
src/open_samus_returns_rando/patcher_editor.py
src/open_samus_returns_rando/specific_patches/chozo_seal_patches.py

Adds new Chozo Seals to areas scenarios which do not have them. These new seals will be strictly used for DNA hints. Seals have been added to the following scenarios:
area3b - Lowest Gamma+ Arena
area5 - Gamma Arena Lower CC
area6b - Top of Tower
area10 - Middle Hallway before the big room
area10 - After the Queen (deactivated until the Queen is defeated)
surfaceb - Before the Teleporter
Unsure how many of these I should add, or if I should add more. I think adding one more earlier on that doesn't require many items could be a good thing. Unsure about adding one in a6/a7 though.

Add custom chozo seals

---

src/open_samus_returns_rando/specific_patches/metroid_patches.py

The `PatcherEditor` uses a dict `memory_files` when using `get_file`. Manipulating the same asset via `get_parsed_asset` + `replace_asset` and at the other code part with `get_file` is bad.
Should change the other usages of `get_parsed_asset` later.

Fix Metroid BMSAD

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

In area2b, if you lay a Power Bomb next the door in `collision_camera009`, the radius of the explosion reaches and breaks the Bomb blocks in `collision_camera012`. If you enter CC12 while the PB is still active, the blocks will be broken and the pickup is visible and can be collected. If you enter CC12 after the PB explosion is gone, the blocks will have been broken, but the block containing `HP_Item_001` despawns, causing the pickup to be lost forever.
This fix avoids this bug by making the pickup freestanding, and then creating a custom Bomb block in place of the pickup block which does not respawn after being broken. In this way, the vanilla behavior is simulated and the pickup is always accessible even if a PB is laid in CC9. The only side effect of this is that the item no longer is …

Prevent `HP_Item_001` from being deleted

---

src/open_samus_returns_rando/files/pickups/randomizermissilelauncher.lua
src/open_samus_returns_rando/files/pickups/randomizermissiletank.lua
src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/files/templates/randomizerpowerup.lua
src/open_samus_returns_rando/lua_editor.py
src/open_samus_returns_rando/specific_patches/static_fixes.py

- Move Launcher Shuffle to `lua_editor`
- Fix default `missiles_per_tank` count
- ~~Disable gun component only if shuffled launcher~~
~~The bug in #276 still exists with this fix, but this at least makes the Missile Reserve Tank fully usable if starting with Missile Launcher. Dunno if we should try to fully fix this in this PR to make it work with shuffled launcher, or just throw a warning in RDV that this bug exists and merge this one for now.~~

Fix Missile Reserve Tanks not refilling Missiles

---

src/open_samus_returns_rando/files/pickups/randomizermissilelauncher.lua
src/open_samus_returns_rando/files/pickups/randomizerreservetankm.lua
src/open_samus_returns_rando/files/templates/custom_init.lua
src/open_samus_returns_rando/files/templates/randomizerpowerup.lua

Given the current implementation of shuffled Missile Launcher, this is the simplest solution to preventing the Missile Reserve Tank from activating on its own without Missiles. Now, it checks for Missile Launcher in the inventory to activate. The only downside is that having only Super Launcher means you can't utilize the Reserve Tank to your advantage. Maybe in the future we can have the Reserve Tank be independent of the Launcher, but this is the best option I'm willing to take for now.
Fixes #253

Only enable Missile Reserve Tank if Missile Launcher is in inventory

---

src/open_samus_returns_rando/files/templates/randomizerpowerup.lua

Fix `ITEM_MISSILE_CHECK` updating to 0 when collecting a tank without launcher

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

A5 has another hidden item that is similar to A2 which can be destroyed from another CC. Since accessing the pickup requires going through a couple CCs, the CC which the actor resides will be reloaded, so no need to add a new block. Just ensure the actor exists in both CCs.

Prevent `s067_area6c: HiddenPowerup002` from being deleted with PB

---

src/open_samus_returns_rando/files/custom/scenario.lua
src/open_samus_returns_rando/files/levels/s030_area3.lua
src/open_samus_returns_rando/files/levels/s033_area3b.lua
src/open_samus_returns_rando/files/levels/s036_area3c.lua
src/open_samus_returns_rando/files/levels/s040_area4.lua
src/open_samus_returns_rando/files/levels/s050_area5.lua
src/open_samus_returns_rando/files/templates/metroid_template.lua
src/open_samus_returns_rando/specific_patches/static_fixes.py
tests/test_files/starter_preset_patcher.json

Reverts https://github.com/randovania/open-samus-returns-rando/pull/287
Makes a change to the SG and SP such that disabling the SG is enough to deactivate the radar.
Activates the TG for the Intro of 007 by default.
Needs to deactivate the trigger as part of the callback to not let the metroid respawn while the metroid setup is still active.
Does this the whole stuff work for 3DS?  Also regarding the whole crash when going to the right of teleporter room? If so, we can work with it further to rework all other multi gammas and get rid of the stupid warping stuff.
Also be aware that disabling the Trigger is just hard coded now...so killing 006 first will deactivate 007.

Proper fix multis

---

src/open_samus_returns_rando/patcher_editor.py
src/open_samus_returns_rando/specific_patches/chozo_seal_patches.py

Just like with shuffled pickups, we have to ensure the new Chozo Seal assets are added to the correct pkgs, otherwise Diggernaut breaks and the fight doesn't end.

Ensure asset dependencies are added to the correct pkgs

---

src/open_samus_returns_rando/files/templates/custom_init.lua
src/open_samus_returns_rando/lua_editor.py

Fixes #310
- Immediately saves the game after load to persistently save reserve tanks as starting items.
- Checks Init.tNewGameInventory for missile launcher shenanigans instead of the blackboard because that is dependent on the order how the values are iterated.
- also checks if the reserve tanks have a value > 0 instead of just the  key being present (I often test by setting the amount to 0 but that didn't work with how the check was done)

Fix reserve tanks as starting items

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

The tile which hides the HiddenPowerup003 was always visible if destroyed from adjacent room and I had no idea how to fix it.
Then I decided to not add the items to any other cc group but just do the "freestanding + place block on top of it" approach for all items.
Haven't looked at all items yet but I leave it here for now.
Fixes #308

Fix for hidden powerups

---

src/open_samus_returns_rando/misc_patches/spawn_points.py

Makes adding new spawns much easier in the future

Use class for adding new spawn points

---

src/open_samus_returns_rando/files/levels/s000_surface.lua
src/open_samus_returns_rando/files/templates/metroid_template.lua

Disable the intro spawn trigger for the newborn alpha if already dead

---

src/open_samus_returns_rando/files/custom/scenario.lua
src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/files/templates/elevators.lua
src/open_samus_returns_rando/misc_patches/elevators.py
src/open_samus_returns_rando/samus_returns_patcher.py
tests/test_files/starter_preset_patcher.json

Allows for the elevator destinations to be shuffled. Fixes #23 
TODO:
- Either add to the schema or some other file

Support Elevator Shuffle

---

src/open_samus_returns_rando/specific_patches/metroid_patches.py

The custom Metroid checkpoints now use a class instead of being individually added. Honestly, this pr might be overkill since I doubt we'd actually add more checkpoints, but could be useful in the future for adding extra boss checkpoints. Either way, cleans up the code a bit so that's a plus.

Refactors the custom Metroid checkpoints

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

Classic how in testing before this didn't come up, but I managed to pull it off from another CC instead 🙃

Hotfix for Beam Block in Surface being deleted

---

src/open_samus_returns_rando/files/levels/s070_area7.lua

Fully ensure PBs can't be used when entering the Diggernaut fight

---

src/open_samus_returns_rando/specific_patches/door_patches.py

Looks like a lot of code  (might be overcomplicated?) but I literally just delete the Door and vanilla spazer shield and copy the shields and door from s000_surface to keep them the same.

Copy door and shield from s000_surface to s110_surfaceb

---

src/open_samus_returns_rando/specific_patches/door_patches.py

Wow, I should have seen when reviewing it.
Plasma doors have the weirdness of them being rotated by 180.0 by default.
All doors are facing left normally but that one is facing right. So, we need to apply a rotation to it because otherwise our logic is bugged and you actually see the ice beam cover intended to be on the right side on the left side.
Fixes #350

Fix ice beam minimap issue

---

src/open_samus_returns_rando/files/custom/scenario.lua

If progressives are enabled and the model is either Wave Beam or High Jump Boots, the model will now face to the right to be more easily identifiable.
Related to #75 (Should close the issue after this)
Wave Beam
High Jump Boots

Rotate Wave Beam and High Jump Boots if progressive

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

Only relevant in Door Lock Rando with Access Open doors shuffled. Falling down the tunnel causes a softlock, so this patch makes that crumble block never respawn. It's technically a non-issue since you never have to take this path, but just in case.

A1 Teleporter Crumble Fix

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

The obstruction in `collision_camera_011` was actually because the pre-chase state is still active initially, so this extends the collision so `collision_camera_001` can be entered in this state. This also allows for the one-way door to be shuffled in DLR.
Fixes #345 
Before:
After:

Patch A4 CM collision for DLR Support

---

src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/samus_returns_patcher.py
src/open_samus_returns_rando/specific_patches/environmental_damage.py
src/open_samus_returns_rando/specific_patches/environmental_damage_sources.py

Setting the third field to be `damage / 2` is completely arbitrary. Could just set it to be damage.

Add support for constant heat/lava damage

---

src/open_samus_returns_rando/files/levels/s100_area10.lua

Current attempt to fix the crash for Reverse Area 8 in RomFS mode. Related to #378
This solution currently checks if the Queen wall exists or not (essentially if RA8 is enabled or disabled). If the option is disabled, vanilla behavior occurs, and the ccs will update their setups when all the Metroids are dead. If it's enabled, never update the setups.
It would be nice to know why this breaks with RomFS mode and not PKG mode instead of doing this, as this is not the most elegant solution, but it does get the job done.

Attempted fix for Reverse Area 8 crash

---

src/open_samus_returns_rando/specific_patches/environmental_damage.py

Damage is now halved to match the tick rate of 0.5 seconds, which fixes the DPS being double the configured value.

Change constant env dps to account for the tick rate

---

src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/files/templates/custom_init.lua
src/open_samus_returns_rando/files/templates/randomizerpowerup.lua
src/open_samus_returns_rando/lua_editor.py
src/open_samus_returns_rando/specific_patches/hint_patches.py
tests/test_files/starter_preset_patcher.json

Reads a string from the configuration which replaces the second sentence with a Baby hint. Will be configurable in Randovania to choose between no hint (current behavior), area only, or precise. Useful as a last resort if in go mode otherwise, or if a Baby hint is not provided

Add hint for Baby location on collected all DNA textbox

---

src/open_samus_returns_rando/files/levels/s010_area1.lua
src/open_samus_returns_rando/files/levels/s030_area3.lua
src/open_samus_returns_rando/files/levels/s040_area4.lua
src/open_samus_returns_rando/files/levels/s090_area9.lua

Vignettes are used to hide sections, and normally aren't an issue. However, with random start/elevators/tricks, some of them become a hindrance and obstruct the player's view. This removes the most problematic ones. More could be removed later if desired.
A1: Break the Bomb Block in the Alpha Arena
A3: Break a shot block below the statue
A4: Break the left Bomb Bomb next to Samus 
A7: Break a Bomb Block above the save to the right near the water

Disable problematic vignettes

---

src/open_samus_returns_rando/files/levels/s010_area1.lua
src/open_samus_returns_rando/files/levels/s030_area3.lua
src/open_samus_returns_rando/files/levels/s040_area4.lua
src/open_samus_returns_rando/files/levels/s090_area9.lua
src/open_samus_returns_rando/specific_patches/static_fixes.py

Removes the references to the vignettes from the appropriate collision_cameras. Also removes the Diggernaut vignette in Area 6 for the start point by the door.
(We should probably go back and improve the parsing of the `bmssd` since it's pretty messy 😛 )
Fixes #393

Fully remove problematic vignettes

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

Hopefully this makes late Bomb seeds a bit more bearable. It was still too low before.

Increase PB Drop Rate to 20% for enemies

---

src/open_samus_returns_rando/files/levels/s100_area10.lua

If going backwards through Area 8, increment the Metroid counter on the first Metroid death only as if the cutscene was watched. This does not get called if going forwards with the cutscene active.
https://github.com/randovania/open-samus-returns-rando/assets/38679103/a38cd95c-00b6-452e-b58b-cbec9839226a
Fixes #404

Increment Metroid count if going through A8 Backwards

---

src/open_samus_returns_rando/files/templates/randomizerpowerup.lua

Re-enables the `SpecialEnergyCloud` for each powerup in a Chozo or Aeion Statue. Special handling was needed for Super Missiles and the Aeion Abilities due to naming issues.
Fixes #104

Re-enable SpecialEnergyCloud for powerups

---

src/open_samus_returns_rando/files/levels/s070_area7.lua
src/open_samus_returns_rando/files/levels/s100_area10.lua
src/open_samus_returns_rando/files/levels/s110_surfaceb.lua

`OnPlayerDead` already handles disabling the low poly on death, but reloading from checkpoint while in a boss fight is not handled in vanilla. This ensures low poly is disabled when a scenario load happens.
Fixes #317

Disable low poly Samus if reloading from checkpoint during boss fight

---

src/open_samus_returns_rando/files/levels/s110_surfaceb.lua
src/open_samus_returns_rando/files/templates/randomizerpowerup.lua

Update the music in Surface West to be Surface East 1 if DNA is not 39 and Baby is not collected, and then uses the regular theme once the conditions to access Ridley are met. The reason for doing this is to add yet another indicator if the seed can be finished.
Debated on doing the 2nd Surface theme to indicate its a later area, but I think the first theme fits better since Landing Site uses that theme.

Surface West Music Changes

---

src/open_samus_returns_rando/cli.py

Add time to patcher cli

---

src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/misc_patches/block_patches.py
src/open_samus_returns_rando/samus_returns_patcher.py

Changes all the blocks of a certain type to another type. Note that will be a chaos option in Randovania, so it will not be logical, but the groundwork for it is there if that ever happens.
Relevant to #409

Support shuffling block types

---

src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/files/templates/custom_init.lua
src/open_samus_returns_rando/files/templates/randomizerpowerup.lua
src/open_samus_returns_rando/lua_editor.py

Finally adding an option so it can be toggled off if desired for whatever reason. Leaving the default to on since that's been the behavior for a long time and too late to change at this point.
Fixes #313

Add toggle for tanks fully refilling ammo

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

Diggernaut has the same issue with the beams just like Ridley. Re-balances Wave and Spazer to use the same factor as Plasma. Only relevant when using Beam Burst for non-Plasma. Merged with the Ridley function.
Looking at the tunables for the Queen, there is no explicit mention of Plasma, so no changes needed there.
Fixes #418

Nerf beams against Diggernaut like with Ridley

---

src/open_samus_returns_rando/patcher_editor.py

The caching causing memory errors in scenarios without a Chozo Seal present, where a custom DNA Seal has been added. This has a side effect of the patcher being ~1-2 seconds slower than before.
Related to #435

Revert caching `get_asset_names_in_folder`

---

src/open_samus_returns_rando/specific_patches/static_fixes.py

Just causes issues when going for the DNA hint and also adds nothing of value
Fixes #426

Area 6 - Delete lower Gullugg from cc42 by DNA Seal

---

src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/specific_patches/cosmetic_patches.py

If someone wants to change the music volume for whatever reason.
Fixes #430

Add option to change the volume of music tracks

---

src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/lua_editor.py

Reworks how `required_dna` is handled to ensure all patcher jsons are compatible.
- Removes the default value from the schema
- Checks for the new configuration field in the json
- If it exists, set the value of `required_dna` to it (new jsons)
- If it doesn't exist, take the difference of 39 and the starting DNA to calculate the required DNA (old jsons)

2nd Attempt at fixing `required_dna` compatibility

---

src/open_samus_returns_rando/files/custom/arachnus.lua
src/open_samus_returns_rando/files/custom/scenario.lua
src/open_samus_returns_rando/files/levels/s000_surface.lua
src/open_samus_returns_rando/files/levels/s020_area2.lua
src/open_samus_returns_rando/files/levels/s070_area7.lua
src/open_samus_returns_rando/files/levels/s100_area10.lua
src/open_samus_returns_rando/files/levels/s110_surfaceb.lua
src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/files/templates/custom_init.lua
src/open_samus_returns_rando/files/templates/randomizerpowerup.lua
src/open_samus_returns_rando/lua_editor.py
src/open_samus_returns_rando/misc_patches/final_boss.py
src/open_samus_returns_rando/misc_patches/triggers.py
src/open_samus_returns_rando/pickups/custom_pickups.py
src/open_samus_returns_rando/pickups/pickup.py
src/open_samus_returns_rando/samus_returns_patcher.py

Okay, so this PR is kinda wild. I've imagined this idea for a while and decided to take a stab at it. It's not very traditional, but it's yet another way to spice up the gameplay up a little bit. With this, any of the four bosses (Arachnus, Diggernaut, Queen, Ridley) can be the final boss! To summarize the changes I made:
- I moved `required_dna` to a new field called `objective` which also lists the boss required to finish.
- Beating the configured boss completes the game and rolls the credits
- Just like with accessing Ridley, accessing the new final boss is also locked to DNA
- If the player doesn't have enough DNA, a message will appear on screen. Arachnus and Diggernaut will warp Samus back to the previous cc
- If Ridley is not the final boss:
- Access to the fight is always active …

Add support for changing the final boss

---

src/open_samus_returns_rando/files/schema.json
src/open_samus_returns_rando/misc_patches/actor_attributes.py
src/open_samus_returns_rando/samus_returns_patcher.py

This PR allows for modifying actor bmsad's via the schema. Currently, changing the `model_scale` of the Baby is supported. We could move other changes we make to actors here as well, but I believe the current changes we make are static changes and never planned to be modified. I'm unsure if this should be more generalized or not or if it could be improved in anyway to be more customizable for rdv/plando purposes.
`model_scale` of 10
`model_scale` of 0.1
Related to #409

Support custom Baby size

---

.pre-commit-config.yaml
src/open_samus_returns_rando/misc_patches/actor_attributes.py
src/open_samus_returns_rando/misc_patches/block_patches.py
src/open_samus_returns_rando/misc_patches/collision_camera_table.py
src/open_samus_returns_rando/misc_patches/credits.py
src/open_samus_returns_rando/misc_patches/elevators.py
src/open_samus_returns_rando/misc_patches/final_boss.py
src/open_samus_returns_rando/misc_patches/lua_util.py
src/open_samus_returns_rando/pickups/custom_pickups.py
src/open_samus_returns_rando/pickups/pickup.py
src/open_samus_returns_rando/specific_patches/chozo_seal_patches.py
src/open_samus_returns_rando/specific_patches/cosmetic_patches.py
src/open_samus_returns_rando/specific_patches/door_patches.py
src/open_samus_returns_rando/specific_patches/game_patches.py
src/open_samus_returns_rando/specific_patches/heat_room_patches.py
src/open_samus_returns_rando/specific_patches/metroid_patches.py
src/open_samus_returns_rando/specific_patches/static_fixes.py
src/open_samus_returns_rando/specific_patches/tunable_patches.py

My vscode uses the bundled ruff and they changed how imports are sorted. Very annoying to see all this errors, so I see if this PR works with a manual version update

Ruff update

---

src/open_samus_returns_rando/files/levels/s110_surfaceb.lua
src/open_samus_returns_rando/files/templates/custom_init.lua
src/open_samus_returns_rando/files/templates/randomizerpowerup.lua

~~base is "cleanup-dnacounter" not main~~

Decrement counter from required_dna to 0

---

src/open_samus_returns_rando/files/custom/scenario.lua

Rotate progressives back

---

src/open_samus_returns_rando/files/custom/heatzone.lua

We have split suits now, so this "fix" needs to be undone.

Make Heat Zone Damage Sound play if you have Gravity again

---

src/open_samus_returns_rando/files/custom/randoapi.lua

- Solo Plasma increased to 85 from 75
- It felt too weak on its own for such a powerful beam so the increase feels necessary
- Plasma + Spazer increased to 90 from 82.5 to account for the Plasma bump
- Spazer shot increases to 270 from 247.5, which still puts it 30 damage lower than vanilla, which still incentivizes Wave
- Plasma + Wave increased to 95 from 90 to account for the previous bump
- This may seem OP, but vanilla is 100 for a single shot and 300 for the Spazer shot, so this still incentivizes Spazer

Rebalance beams

---

src/open_samus_returns_rando/lua_editor.py

~Now properly gets the default value if not present. Before it was saying `configuration[configuration["final_boss_hint"]]`~
Now ensures that a message is provided regardless,

Fix configuration default for `final_boss_hint`

---

src/open_samus_returns_rando/specific_patches/cosmetic_patches.py

Music Shuffle now properly modifies the bmdefs file directly instead of lazily making copies of the sound files and renaming them. This saves a whopping 164-174 MB of storage, which will greatly improve export times to 3DS if enabled! This has the added benefit of keeping the correct volume for each track instead of just inheriting the old one, which made some sounds too loud or too quiet.
Fixes #539

Better implementation of Music Shuffle
