- open_samus_returns_rando/files/levels/s110_surfaceb.lc.lua
Make the Ridley fight not trigger in any regard (force reposition, cutscene, boss spawning) if Metroid count is greater than 0.
> Ridley fight requirements.

- open_samus_returns_rando/files/levels/s000_surface.lua
- open_samus_returns_rando/files/levels/s010_area1.lua
- open_samus_returns_rando/files/levels/s020_area2.lua
- open_samus_returns_rando/files/levels/s025_area2b.lua
- open_samus_returns_rando/files/levels/s028_area2c.lua
- open_samus_returns_rando/files/levels/s030_area3.lua
- open_samus_returns_rando/files/levels/s033_area3b.lua
- open_samus_returns_rando/files/levels/s036_area3c.lua
- open_samus_returns_rando/files/levels/s040_area4.lua
- open_samus_returns_rando/files/levels/s050_area5.lua
- open_samus_returns_rando/files/levels/s060_area6.lua
- open_samus_returns_rando/files/levels/s065_area6b.lua
- open_samus_returns_rando/files/levels/s067_area6c.lua
- open_samus_returns_rando/files/levels/s070_area7.lua
- open_samus_returns_rando/files/levels/s090_area9.lua
> Prevent doors from locking during evolved Metroid fights

- open_samus_returns_rando/files/schema.json
- open_samus_returns_rando/samus_returns_patcher.py
- open_samus_returns_rando/templates/custom_init.lua
Maybe should removed later as it is revealing everything but maybe nice to have debug feature for now
Depends on #50
> Add reveal map debug feature

- open_samus_returns_rando/files/schema.json
- open_samus_returns_rando/specific_patches/game_patches.py
https://github.com/randovania/open-samus-returns-rando/assets/38679103/8c9a8cb6-19c3-4f98-9513-86b11fa6a322
> Option to make Missile shields not open to Super Missiles

- open_samus_returns_rando/files/randomizer_powerup.lua
- open_samus_returns_rando/lua_editor.py
> Fix collecting aeion items

- open_samus_returns_rando/model_data.py
> Fix (last?) dependencies of SJ

- open_samus_returns_rando/files/schema.json
My patcher file was not complaining but the patcher crashed. Looks like it is now required :p
> Add ITEM_MAX_SPECIAL_ENERGY as required

- open_samus_returns_rando/files/levels/s050_area5.lua
They forgot to change a bool lol
New
Old
> Fix incorrect tank placement in Diggernaut Chase Arena

- open_samus_returns_rando/patcher_editor.py
- open_samus_returns_rando/samus_returns_patcher.py
I decided to split all these changes and not do everything in the door branches (door branch will be rebased later)
> Update for new main MEDS

- open_samus_returns_rando/files/levels/s030_area3.lua
- open_samus_returns_rando/specific_patches/static_fixes.py
> Patch Area 3 Gamma to spawn/remain in one room

- open_samus_returns_rando/files/doors.lua
- open_samus_returns_rando/files/randomizer_powerup.lua
- open_samus_returns_rando/samus_returns_patcher.py
- open_samus_returns_rando/specific_patches/door_patches.py
- tests/test_files/thanatos_dev.json
- tests/test_files/thanatos_dev_heat_5_1.json
Needs to be tested at some point.
I had my favourite bug that a door creature (actor) disappeared when entering a room BUT it was only happening when I glitched through the wall with a cheat. 
Maybe the game is just confused when I get to a room where the only way to this room was via a door, which I'm passing by moving above it through the wall
> Door and Shield Patches

- open_samus_returns_rando/specific_patches/door_patches.py
It sucks but I run into some issues again. Wtf is wrong with adding actors to entity groups  😥
(two lines were too long according to ruff)
> Remove new doors from entity groups

- open_samus_returns_rando/files/schema.json
- open_samus_returns_rando/misc_patches/credits.py
- open_samus_returns_rando/samus_returns_patcher.py
> Add credits

- open_samus_returns_rando/files/randomizer_powerup.lua
Untested. Won't test this today anymore.
At least it works delayed, hopefully it also works directly without delay.
Fixes #40
> Move baby to samus

- open_samus_returns_rando/model_data.py
This should be the last model dependency PR we need to make 😛 
Fixes #132
> Add missing itemsphere dependency

- open_samus_returns_rando/misc_patches/text_patches.py
- open_samus_returns_rando/samus_returns_patcher.py
https://github.com/randovania/open-samus-returns-rando/assets/38679103/3ca5831c-8c1e-4fa4-8222-e04d055ec45a
> Add unused gui text regarding Spider Boost technique

- open_samus_returns_rando/files/levels/s025_area2b.lua
- open_samus_returns_rando/specific_patches/metroid_patches.py
Creates a new trigger and two new checkpoints on the right side entrance for the area2b Gamma
> Create new checkpoint for entering 2b Gamma from right

- open_samus_returns_rando/files/custom_savestation.lua
- open_samus_returns_rando/files/custom_ship.lua
- open_samus_returns_rando/files/levels/s000_surface.lua
- open_samus_returns_rando/files/templates/metroid_template.lua
- open_samus_returns_rando/misc_patches/text_patches.py
- Metroid icon keeps deactivated
- CC setup does not change after defeating surface metroid
> Fix surface stuff and ruff

- open_samus_returns_rando/pickup.py
> Distribute files to correct pkg

- open_samus_returns_rando/files/schema.json
- open_samus_returns_rando/specific_patches/game_patches.py
- Can now toggle if pbs can break beam doors or charge doors
- Cleaned up grapple config so the pull blocks now get moved instead of destroyed
> Cleanup game_patches and split pb patches

- open_samus_returns_rando/specific_patches/static_fixes.py
Removes a softlock without Grapple
> Remove Grapple Block below A7 Chozo Seal

- open_samus_returns_rando/constants.py
- open_samus_returns_rando/files/levels/s000_surface.lua
- open_samus_returns_rando/files/levels/s010_area1.lua
- open_samus_returns_rando/files/levels/s028_area2c.lua
- open_samus_returns_rando/files/levels/s030_area3.lua
- open_samus_returns_rando/files/levels/s040_area4.lua
- open_samus_returns_rando/files/levels/s060_area6.lua
- open_samus_returns_rando/files/levels/s070_area7.lua
- open_samus_returns_rando/files/levels/s090_area9.lua
- open_samus_returns_rando/files/templates/custom_init.lua
- open_samus_returns_rando/model_data.py
- open_samus_returns_rando/pickup.py
- open_samus_returns_rando/specific_patches/door_patches.py
- open_samus_returns_rando/specific_patches/map_icons.py
- open_samus_returns_rando/specific_patches/metroid_patches.py
The branch name says it all.
On a more serious note: I try to be less intrusive with the changes. Change as less as possible but as much as needed.
Especially with the rando has a random infinite loading screen, which happens most of the time approx. after 3-4 h but never with the vanilla game.
That's also why I restored some of the original lua because I compare it from time to time and not needed random changes are distracting.
Maybe there will follow some similar PRs from time to time.
> Random changes

- open_samus_returns_rando/specific_patches/map_icons.py
Now accounts for all door changes and is more simplified
> Fix map icons function

- open_samus_returns_rando/specific_patches/door_patches.py
- open_samus_returns_rando/specific_patches/map_icons.py
Restores two Charge Doors to help improve item balancing and reduce some openness
- s050_area5 entrance
- s070_area7 top
> Revert some Charge Doors

- open_samus_returns_rando/files/custom_heatzone.lua
- open_samus_returns_rando/files/custom_scenario.lua
- open_samus_returns_rando/files/doors.lua
- open_samus_returns_rando/files/levels/s040_area4.lua
- open_samus_returns_rando/files/randomizer_powerup.lua
- open_samus_returns_rando/files/templates/metroid_template.lua
- open_samus_returns_rando/files/templates/template_powerup_bmsad.json
- open_samus_returns_rando/specific_patches/door_patches.py
We need to check for `SpawnGroup020` and `SpawnGroup021` because I'm sure that this was throwing also errors when very close to the door,
Should also be rebased later.
> Fix unmapped reads / writes

- open_samus_returns_rando/specific_patches/map_icons.py
Support edge case where len is 2 and first object is a tank
> Fix map tiles

- src/open_samus_returns_rando/files/custom_scenario.lua
- src/open_samus_returns_rando/files/schema.json
- src/open_samus_returns_rando/files/templates/custom_init.lua
- src/open_samus_returns_rando/lua_editor.py
- src/open_samus_returns_rando/misc_patches/text_patches.py
- tests/test_files/starter_preset_patcher.json
https://github.com/randovania/open-samus-returns-rando/assets/117127188/33248dd6-bed4-44f0-9295-6dc9b7843ecb
> Add message for starting items

- src/open_samus_returns_rando/files/levels/s100_area10.lua
Makes this section feel more important again and is more accurate without taking away anything
(Also fixes an input bug which I'd rather just fix by renabling what was disabled 😛 )
> Renable Larva cutscene + counter increase

- src/open_samus_returns_rando/files/custom_savestation.lua
- src/open_samus_returns_rando/files/custom_scenario.lua
- src/open_samus_returns_rando/files/custom_ship.lua
- src/open_samus_returns_rando/files/levels/s000_surface.lua
- src/open_samus_returns_rando/files/levels/s110_surfaceb.lua
> Fix crash from west to east

- src/open_samus_returns_rando/files/custom_scenario.lua
> Exit IdleScreen when starting to fix random start at saves

- src/open_samus_returns_rando/files/levels/s040_area4.lua
- src/open_samus_returns_rando/files/templates/metroid_template.lua
Also adds a fade in and disables input temporarily
> Fix a4 gamma teleport occuring more than once

- src/open_samus_returns_rando/files/custom_scenario.lua
- src/open_samus_returns_rando/files/guilib.lua
- src/open_samus_returns_rando/files/templates/randomizer_powerup.lua
Notifies the player if they can have enough DNA to unlock Ridley. Adds two variants: All DNA with Baby, All DNA no Baby
https://github.com/randovania/open-samus-returns-rando/assets/38679103/ac52e58b-2716-4c59-9a17-505ea9786453
https://github.com/randovania/open-samus-returns-rando/assets/38679103/5d850504-b0d0-4467-b9d1-50e8daf13850
Also changes the color of the total DNA counter when all DNA is collected
https://github.com/randovania/open-samus-returns-rando/assets/38679103/3c54cf67-2b8a-411b-86e2-ed8da20077df
> Display message when all DNA is collected

- src/open_samus_returns_rando/files/templates/template_powerup_bmsad.json
> Update fields in `template_powerup_bmsad.json`

- src/open_samus_returns_rando/specific_patches/static_fixes.py
Don't know when or if I will test it. But we have beta testers :)
(raising it for wave beam and plasma beam was working)
> Nerf beams against ridley

- src/open_samus_returns_rando/files/schema.json
- src/open_samus_returns_rando/specific_patches/game_patches.py
- tests/test_files/starter_preset_patcher.json
`beam_burst_buff` is a more accurate name for the configuration
> Rename plant_buff configuration

- src/open_samus_returns_rando/specific_patches/map_icons.py
Ensures the removed Charge Doors are properly Power on the map again :)
> Map Fix Fix Fix

- src/open_samus_returns_rando/files/schema.json
It's supposed to be Blue, not Yellow (oops)
> Fix incorrect default values for `vGrappleLaserLockedColor0`

- src/open_samus_returns_rando/files/levels/s100_area10.lua
Forgot to change this when moving the first seal in A8 to A6
> Update Queen seal name since one seal in A8

- tests/test_files/item_models_test.json
- tests/test_files/starter_preset_patcher.json
- Updates `starter_preset_patcher.json` to match the current exporting features of RDV
- Adds `item_models_test.json` for quick and easy testing of item models. This is good for testing new models in game (we had this file before but we removed it)
> Update/Add Test Files

- src/open_samus_returns_rando/pickups/custom_pickups.py
Future Proofing (I swear this is the last one 😛 )
> Refactor Custom Pickups

- src/open_samus_returns_rando/specific_patches/door_patches.py
> Fix creature doors not being removed

- src/open_samus_returns_rando/specific_patches/door_patches.py
- Fixes new door weaknesses not being applied
- Fixes Ice Shields missing Plasma Shield assets
> Door Lock Fixes

- pyproject.toml
- src/open_samus_returns_rando/specific_patches/door_patches.py
- src/open_samus_returns_rando/specific_patches/metroid_patches.py
Missing a (unreleased) MEDS bump
> Support for new MEDS

- src/open_samus_returns_rando/samus_returns_patcher.py
> Really delete old files

- src/open_samus_returns_rando/files/templates/randomizerpowerup.lua
> Special case for Surface West shared pickups

- src/open_samus_returns_rando/files/levels/s070_area7.lua
Relevant if starting in upper A6
> Enable A6 Omega by default

- src/open_samus_returns_rando/files/schema.json
- src/open_samus_returns_rando/specific_patches/cosmetic_patches.py
Takes a dictionary of tracks as input and replaces the data with a new specified track
Fixes #69
> Support Music Shuffle

- src/open_samus_returns_rando/specific_patches/static_fixes.py
There was another model unaccounted for 🙃. Is there a better way to simplify this whole function? It's rather messy.
> A7 Save Station Blocks Edge Case

- src/open_samus_returns_rando/specific_patches/static_fixes.py
With profiler overhead, this about 3.5 times faster.
> Improve disable_vignettes

- src/open_samus_returns_rando/patcher_editor.py
Significantly speed-ups DoorPatches
> Cache get_asset_names_in_folder

- src/open_samus_returns_rando/files/schema.json
- src/open_samus_returns_rando/samus_returns_patcher.py
- src/open_samus_returns_rando/specific_patches/tunable_patches.py
> Add support for custom damage reduction per suit

- src/open_samus_returns_rando/specific_patches/static_fixes.py
Totally didn't forget to update one variable name for the latest MEDS. Nah, couldn't be me......... 🙃 
Fixes #445
> Fix vignettes not being removed (again)

- src/open_samus_returns_rando/files/custom/guilib.lua
> Fix Disconnected message does not work correctly

- src/open_samus_returns_rando/misc_patches/final_boss.py
> Add Queen trigger to the correct entity_group

- src/open_samus_returns_rando/files/schema.json
- src/open_samus_returns_rando/lua_editor.py
> Have schema determine what sound plays when a pickup is picked up

- src/open_samus_returns_rando/files/custom/scenario.lua
- src/open_samus_returns_rando/files/levels/s070_area7.lua
- src/open_samus_returns_rando/files/templates/custom_init.lua
Also cleans up some minor related things
> Display number of DNA left in boss message popup

- src/open_samus_returns_rando/lua_editor.py
> Validate starting actor exists

- src/open_samus_returns_rando/files/schema.json
- src/open_samus_returns_rando/lua_editor.py
Fixes https://discord.com/channels/914291389293027329/1386412573498282024 
Depending on the settings used, DNA could be given as random starting items with no other DNA placed in the world. This should account for all cases of different combinations of starting DNA and required DNA.
> Account for varying starting/objective DNA amounts
